# Generated by Django 5.0.3 on 2024-03-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat", name="legs", field=models.IntegerField(default=4),
        ),
    ]
